name: Keycloak CI

on:
  push:
    paths:
      - "devops/keycloak/**"
      - ".github/workflows/keycloak.yml"
  workflow_dispatch:

env:
  IMAGE_NAME_PREFIX: ghcr.io/ericof/portal-documentacao
  IMAGE_NAME_SUFFIX: keycloak

jobs:
  meta:
    runs-on: ubuntu-latest
    outputs:
      BASE_TAG: ${{ steps.vars.outputs.BASE_TAG }}
      KEYCLOAK_VERSION: ${{ steps.vars.outputs.KEYCLOAK_VERSION }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Compute several vars needed for the build
        id: vars
        run: |
          echo 'BASE_TAG=sha-$(git rev-parse --short HEAD)' >> $GITHUB_OUTPUT
          echo "KEYCLOAK_VERSION=$(cat devops/keycloak/version.txt)" >> $GITHUB_OUTPUT

      - name: Test vars
        run: |
          echo 'BASE_TAG=${{ steps.vars.outputs.BASE_TAG }}'
          echo 'KEYCLOAK_VERSION=${{ steps.vars.outputs.KEYCLOAK_VERSION }}'

  release:
    runs-on: ubuntu-latest
    needs:
      - meta
    permissions:
      contents: read
      packages: write

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.IMAGE_NAME_PREFIX }}-${{ env.IMAGE_NAME_SUFFIX }}
          labels: |
            org.label-schema.docker.cmd=docker run -d -p 8180:8080 ${{ env.IMAGE_NAME_PREFIX }}-${{ env.IMAGE_NAME_SUFFIX }}:latest
          flavor:
            latest=false
          tags: |
            type=ref,event=branch
            type=sha
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64
          context: devops/keycloak/
          file: devops/keycloak/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            KEYCLOAK_VERSION=${{ needs.meta.outputs.KEYCLOAK_VERSION }}
